### ISSUE TITLE
v0.3.0 fails to build with libc++

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprlock#289]
Regressed by #247. Affects libc++ 16/17/18 (didn't test trunk). Note, [count()](https://en.cppreference.com/w/cpp/chrono/duration/count) example builds fine.

```c++
$ export CXX=clang++ CXXFLAGS=-stdlib=libc++
$ cmake -B /tmp/hyprlock_build
$ cmake --build /tmp/hyprlock_build
[...]
src/renderer/widgets/Image.cpp:55:67: error: call to 'to_string' is ambiguous
   55 |     request.id        = std::string{"image:"} + path + ",time:" + std::to_string(modificationTime.time_since_epoch().count());
      |                                                                   ^~~~~~~~~~~~~~
/usr/include/c++/v1/string:4009:34: note: candidate function
 4009 | _LIBCPP_EXPORTED_FROM_ABI string to_string(int __val);
      |                                  ^
/usr/include/c++/v1/string:4010:34: note: candidate function
 4010 | _LIBCPP_EXPORTED_FROM_ABI string to_string(unsigned __val);
      |                                  ^
/usr/include/c++/v1/string:4011:34: note: candidate function
 4011 | _LIBCPP_EXPORTED_FROM_ABI string to_string(long __val);
      |                                  ^
/usr/include/c++/v1/string:4012:34: note: candidate function
 4012 | _LIBCPP_EXPORTED_FROM_ABI string to_string(unsigned long __val);
      |                                  ^
/usr/include/c++/v1/string:4013:34: note: candidate function
 4013 | _LIBCPP_EXPORTED_FROM_ABI string to_string(long long __val);
      |                                  ^
/usr/include/c++/v1/string:4014:34: note: candidate function
 4014 | _LIBCPP_EXPORTED_FROM_ABI string to_string(unsigned long long __val);
      |                                  ^
/usr/include/c++/v1/string:4015:34: note: candidate function
 4015 | _LIBCPP_EXPORTED_FROM_ABI string to_string(float __val);
      |                                  ^
/usr/include/c++/v1/string:4016:34: note: candidate function
 4016 | _LIBCPP_EXPORTED_FROM_ABI string to_string(double __val);
      |                                  ^
/usr/include/c++/v1/string:4017:34: note: candidate function
 4017 | _LIBCPP_EXPORTED_FROM_ABI string to_string(long double __val);
      |                                  ^
```
